---
uv_release_api_url: https://api.github.com/repos/astral-sh/uv/releases/latest
uv_release_base_url: https://github.com/astral-sh/uv/releases/download
uv_install_directory: /usr/local/bin

uv_architecture_map:
  x86_64: x86_64
  amd64: x86_64
  aarch64: aarch64
  arm64: aarch64
