---
# Desktop-specific packages

- name: Add user to kvm group
  ansible.builtin.user:
    name: "{{ user_name }}"
    groups: kvm
    append: true

- name: Install ChatGPT Desktop
  ansible.builtin.include_role:
    name: chatgpt

- name: Install Claude Desktop
  ansible.builtin.include_role:
    name: claude_desktop

- name: Install Visual Studio Code
  ansible.builtin.include_role:
    name: vscode

- name: Install MEGA Desktop App
  ansible.builtin.include_role:
    name: megasync

- name: Install Discord
  ansible.builtin.include_role:
    name: discord
  when: linux_release_architecture_map[ansible_facts["architecture"]] == "amd64"

- name: Install Posit RStudio Desktop
  ansible.builtin.include_role:
    name: rstudio
  when: linux_release_architecture_map[ansible_facts["architecture"]] == "amd64"

- name: Install Zoom Workplace
  ansible.builtin.include_role:
    name: zoom
  when: linux_release_architecture_map[ansible_facts["architecture"]] == "amd64"

- name: Install LibreOffice
  ansible.builtin.apt:
    name: libreoffice
    state: present
    update_cache: true
