---
# Desktop-specific packages

- name: Add user to kvm group
  ansible.builtin.user:
    name: "{{ user_name }}"
    groups: kvm
    append: true

- name: Install ChatGPT Desktop
  ansible.builtin.include_role:
    name: chatgpt

- name: Install Claude Desktop
  ansible.builtin.include_role:
    name: claude_desktop

- name: Install Posit RStudio Desktop
  ansible.builtin.include_role:
    name: rstudio

- name: Install Desktop Packages
  ansible.builtin.apt:
    name:
      - openssh-server
      - libreoffice
    state: present
    update_cache: true
