---
# Desktop (non-WSL) specific packages

- name: Install Desktop Packages
  ansible.builtin.apt:
    name:
      - openssh-server
      - fonts-firacode
      - libreoffice
    state: present

- name: Install Classic Snaps
  community.general.snap:
    name:
      - code
    classic: true

- name: Install Snaps
  community.general.snap:
    name:
      - chromium
      - discord
      - steam
      - zoom-client
