---
vscode_repository:
  display_name: Visual Studio Code
  package_names:
    - code
  url: https://packages.microsoft.com/repos/code
  suites: stable
  components: main
  sources_path: /etc/apt/sources.list.d/vscode.sources
  keyring_path: /usr/share/keyrings/microsoft-vscode.gpg
  key_fingerprint: BC528686B50D79E339D3721CEB3E94ADBE1229CF
  key_url: https://packages.microsoft.com/keys/microsoft.asc
  legacy_sources_path: /etc/apt/sources.list.d/vscode.list
