---
ty_release_api_url: https://api.github.com/repos/astral-sh/ty/releases/latest
ty_release_base_url: https://github.com/astral-sh/ty/releases/download
ty_install_directory: /usr/local/bin

ty_architecture_map:
  x86_64: x86_64
  amd64: x86_64
  aarch64: aarch64
  arm64: aarch64
